name: CKAN Harvest
type: ckan
input_csv: inputs/harvest-workflow-inputs/py-ckan.csv
hub_metadata_csv: reference_data/websites.csv
rows: 100
timeout: 60
output_primary_csv: outputs/ckan_primary.csv
output_distributions_csv: outputs/ckan_distributions.csv
output_report_csv: reports/ckan/ckan_report.csv
build_uploads: true
